module.exports = {
    'didn t': 'didnt',
    'don t': 'dont',
    'i m': 'im',
    'can t': 'cant',

    'fake smiles': 'frowns',
    'fake my smiles': 'frowns',
    'fake your smiles': 'frowns',
    'fake smile': 'frowns',
    'fake love': 'dislike',
    'fake happiness': 'sadness',
    'fake news': 'misinformation',
    'fake friendly': 'unauthentic',
    'fake my happiness': 'sadness',
    'fake happiness': 'sadness',
    'fake humour': 'seriousness',

    'not feeling terrific': 'feeling lousy',
    'not feeling wonderful': 'feeling lousy',
    'not feeling great': 'feeling lousy',
    'not feeling awesome': 'feeling lousy',
    'not feeling fantasic': 'feeling lousy',
    'not feeling swell': 'feeling lousy',
    'not feeling good': 'feeling lousy',
    'not feeling ok': 'feeling lousy',
    'not feeling okay': 'feeling lousy',
    'not feeling very': 'feeling not',
    'not feeling better': 'feeling lousy',
    'not feeling ignored': 'feeling attended to',
    'not feeling bitter': 'feeling ok',
    'not feeling apprehensive': 'insensible',
    'not feeling afraid': 'insensible',
    'not feeling fearful': 'insensible',
    'not feeling alarmed': 'insensible',
    'not feeling dread': 'insensible',
    'not feeling fearsome': 'insensible',
    'not feeling fear': 'insensible',
    'not feeling forbodding': 'insensible',
    'not feeling frightened': 'insensible',
    'not feeling intimidated': 'insensible',
    'not feeling scared': 'insensible',
    'not feeling terrible': 'insensible',
    'not feeling terrified': 'insensible',

    'not feel terrific': 'feel lousy',
    'not feel wonderful': 'feel lousy',
    'not feel great': 'feel lousy',
    'not feel awesome': 'feel lousy',
    'not feel fantasic': 'feel lousy',
    'not feel swell': 'feel lousy',
    'not feel good': 'feel lousy',
    'not feel ok': 'feel lousy',
    'not feel okay': 'feel lousy',
    'not feel very': 'feel not',
    'not feel better': 'feel lousy',
    'not feel ignored': 'feel attended to',
    'not feel bitter': 'feel ok',
    'not feel apprehensive': 'insensible',
    'not feel afraid': 'insensible',
    'not feel fearful': 'insensible',
    'not feel alarmed': 'insensible',
    'not feel dread': 'insensible',
    'not feel fearsome': 'insensible',
    'not feel fear': 'insensible',
    'not feel forbodding': 'insensible',
    'not feel frightened': 'insensible',
    'not feel intimidated': 'insensible',
    'not feel scared': 'insensible',
    'not feel terrible': 'insensible',
    'not feel terrified': 'insensible',
    'not a very faithful': 'unfaithful',
    'not very faithful': 'unfaithful',
    'not completely': 'somewhat',
    'not always': 'somewhat',
    'not because': 'regardless',
    'not always': 'seldem',
    'not well enough informed': 'uninformed',
    'not well informed': 'uninformed',
    'not in a good place': 'bad place',
    'not very': 'not',
    'not this': 'not',
    'not going to be': 'not',
    // 'not to be too': '',
    'not being competent': 'incompetent',
    'not much': 'little',
    'not fail': 'performed sufficiently',
    'not feel sympathetic': 'unsympathetic',
    'not lighting my world on fire': 'satisfactory',
    'didnt feel comfortable': 'felt uncomfortable',
    'didnt feel safe': 'felt unsafe',
    'didnt feel particularly': 'not ',
    'didnt feel': 'not ',

    'nothing special': 'inadequate',
    'nothing amazing': 'inadequate',
    'nothing astonishing': 'inadequate',
    'nothing astounding': 'inadequate',

    'feel like a fake': 'feel unauthentic',
    'smile is fake': 'frowns',

    'not being as': 'not',
    'not being': 'not',
    'not particularly': 'not',
    'not feel that': 'not',
    'not so': 'not',
    'not be': 'not',
    'not feel': 'not',
    'dont feel as': 'not',
    'didnt feel as': 'not',
    'didnt feel so': 'not',
    'dont feel so': 'not',
    'didnt feel': 'not',
    'don t feel': 'not',
    'dont feel': 'not',
    'not feeling': 'unconcern',
    'not well informed': 'uninformed',
    'not a good idea': 'a dissatisfactory idea',
    'not a bad idea': 'a good idea',

    'not afraid': 'secure',
    'not alarmed': 'secure',
    'not fearful': 'secure',
    'not frightened': 'safe',
    'not horrified': 'secure',
    'not hysterical': 'secure',
    'not hysteric': 'secure',
    'not scary': 'secure',
    'not shocked': 'calm',
    'not spooked': 'secure',
    'not terrified': 'secure',
    'not angry': 'tolerant',
    'not bothered': 'content',
    'not compare': 'contrast',
    'not content': 'uncontent',
    'not calm': 'agitated',
    'not peaceful': 'warlike',
    'not serene': 'loud',
    'not tranquil': 'loud',
    'not dead': 'undead',
    'not happy': 'unhappy',
    'not sad': 'ok',
    'not bad': 'ok',
    'not good': 'bad',
    'not great': 'bad',
    'not awesome': 'bad',
    'not wonderful': 'bad',
    'not fantasic': 'bad',
    'not swell': 'bad',
    'not ok': 'bad',
    'not okay': 'bad',
    'not pleasant': 'unpleasant',
    'not satisfied': 'unsatisfied',
    'not thrilled': 'cheerless',
    'not compassionate': 'uncompassionate',
    'not wanting': 'hesitant',
    'not jealous': 'content',
    'not contributing': 'subtracting',
    'not motivated': 'unmotivated',
    'not respected': 'disreputable',
    'not separately': 'collocated',
    'not well': 'unwell',
    'not better': 'worse',
    'not sure': 'unsure',
    'not alone': 'supported',
    'not smart': 'incompetent',
    'not clever': 'incompetent',
    'not competent': 'incompetent',
    'not convinced': 'unconvinced',
    'not faithful': 'unfaithful',
    'not stupid': 'competent',
    'not sympathetic': 'unsympathetic',
    'not informed': 'uninformed',
    'not deserving': 'undeserving',
    'not carefree': 'controlled',
    'not hopeful': 'pessimistic',
    'not lonely': 'accompanied',
    'not strong enough': 'weak',
    'not strong': 'incapable',
    'not intimidated': 'strong',
    'not burdened': 'unencumbered',
    'not weighed down': 'unencumbered',
    'not funny': 'humorless',

    'didnt care': 'apathy',
    'didnt love': 'disliked',
    'didnt like': 'disliked',
    'didnt hate': 'accept',
    'dont care': 'apathy',
    'dont love': 'dislike',
    'dont like': 'dislike',
    'dont hate': 'accept',

    'not in a bad mood': 'in a decent mood',
    'not in a good mood': 'in a poorly mood',

    'no respected': 'disfavour',

    'http': '',
    'www': '',
    'href': '',
    'fake email': '',
    'email': '',
};